CREATE TABLE "books" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "books_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"title" text NOT NULL,
	"wordCount" integer NOT NULL,
	"coverUrl" text NOT NULL,
	"bookId" text NOT NULL,
	"tags" text[] DEFAULT '{}'::text[] NOT NULL,
	CONSTRAINT "books_book_id_unique" UNIQUE("bookId"),
	CONSTRAINT "books_word_count_nonnegative" CHECK ("books"."wordCount" >= 0)
);
--> statement-breakpoint
INSERT INTO "books" ("title", "wordCount", "coverUrl", "bookId", "tags")
SELECT "bookId", count(*)::integer, '', "bookId", '{}'::text[]
FROM "words"
WHERE "bookId" IS NOT NULL
GROUP BY "bookId";
--> statement-breakpoint
ALTER TABLE "words" ADD CONSTRAINT "words_bookId_books_bookId_fk" FOREIGN KEY ("bookId") REFERENCES "public"."books"("bookId") ON DELETE restrict ON UPDATE cascade;--> statement-breakpoint
CREATE INDEX "words_book_id_idx" ON "words" USING btree ("bookId");
